// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntcbxmiguaygcpippxpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Y2J4bWlndWF5Z2NwaXBweHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDMxNDQsImV4cCI6MjA3NDM3OTE0NH0.ixNj2s01POjRqZFTm3RAj1HUZAptCtshKXm6UAF52o0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});